# Default values for springboot app demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: sb-app
replicaCount: 1
application_domain:
  
image:
  name: operator-test
  repository: helm-operator-demo/operator-test
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: sb-app-service
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
ingress:
  enabled: false
resources: {}
